### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by danni**
Documentation generated with Sphinx.

### CODE REVIEW

**Comment by koterpillar** [comment]
Descriptions are usually complete sentences and as such should end with periods.

Pylint is right on both accounts, but it's OK to ignore the "too many lines" - parser needs refactoring anyway.

README that is duplicated in the new docs should be slashed away.

**Comment by koterpillar** [comment]
Also, I already dislike Sphinx for needing so many configuration files, but since it's a de facto standard, I guess they know better.

**Comment by danni** [comment]
Let's update the readme once there's links to RTD.

Sphinx only has one config file. The makefile is optional.

**Comment by koterpillar** [comment]
Fixed your filen and merged.

**Pull request merged**
