### PR TITLE
Removed monkey patching of the standard library.

### PR DESCRIPTION
**Pull request by chrishaines**
This gets rid of unintended side effects.

### CODE REVIEW

**Comment by koterpillar** [comment]
Just curious, what are the side effects you're talking about?

**Comment by chrishaines** [comment]
@koterpillar install_aliases adds `request` to the `urllib` module. This causes problems with libraries that use it to do python 3 checking. For example, in https://github.com/miracle2k/webassets/blob/master/src/webassets/merge.py

``` python
try:
    from urllib.request import Request as URLRequest, urlopen
    from urllib.error import HTTPError
except ImportError:
    from urllib2 import Request as URLRequest, urlopen
    from urllib2 import HTTPError
```

makes it incorrectly infer that it running on python 3. While this should work regardless, I don't think that aloe should make other libraries stop working because of bugs in their python 3 compatibility.

**Comment by koterpillar** [comment]
That example will actually work fine with future, but I agree, global changes shouldn't happen when just using a library.

**Comment by koterpillar** [comment]
I'll go through `aloe_django` and `aloe_webdriver` to remove the same from them.

**Pull request merged**
