### PR TITLE
Export Scenario as a step

### PR DESCRIPTION
**Pull request by massudaw**
If we use the scenario name as a regex pattern and all scenarios steps executed as the Step function we can get a kind of macro system for blocks of steps. I found this really useful for abstracting  blocks of application logic into smaller steps.

For example: 

    Scenario Outline : Multiple steps "([^"]*)"  
        Given First Step <name>
        And Second Step <name>
    Examples:
        | name |
        | Foo  |
    Scenario: Call Scenario
        Given Multiple steps Foo

Follows a simple implementation of the idea.  Any comments appreciated.

### CODE REVIEW

**Comment by koterpillar** [comment]
Thank you for the contribution!

Unfortunately, I'm not sure what functionality is added here. Can you please make the changes to the documentation and tests that illustrate what can you do with this patch?

Also, it looks like `behave_as` is doing most of what you want already. You can define something like:

```python
@step(r'Multiple steps "([^"]*)"')
def multiple_steps(self, name):
    self.when("First step {}".format(name))
    self.when("Second step {}".format(name))
```

**Comment by massudaw** [comment]
This feature allows us to reuse scenario outlines as steps. Because a scenario outline is parametrized, if we name it as a regex, we can use the regex to extract the values  needed to parametrize the outline. 

You can use behave_as() to achieve the same functionality in python. The main cons of it is that you need to duplicate the code. to redefine combinations and then create new features to test then. With this feature you can define smaller independent scenarios and reuse then composing larger ones.

**Comment by koterpillar** [comment]
This can be done without messing with the parser, by implementing a custom step. Just make a step that matches `Run scenario (.+)` as the regular expression, get access to the feature you are running in via `self.feature` in the step function and do all the variable replacing you need.

The existing code in this PR has issues - please look at the Travis CI build. Also, given that Aloe is a behavior _driven_ development tool, it would make sense to write some tests first.

**Comment by koterpillar** [comment]
Please reopen when you have addressed the comments.

**Comment by koterpillar** [comment]
Please reopen when you have addressed the comments.

**Pull request closed without merging**
